CREATE TABLE STUDENT (
    STUDENT_NUMBER INTEGER,
    NAME VARCHAR2(255),
    CLASS INTEGER,
    MAJOR VARCHAR2(20),
    PRIMARY KEY (STUDENT_NUMBER)
)

CREATE TABLE COURSE (
    COURSE_NAME VARCHAR2(255),
    COURSE_NUMBER VARCHAR2(20),
    CREADIT_HOURS INTEGER,
    DEPARTMENT VARCHAR2(20),
    PRIMARY KEY (COURSE_NUMBER)
)

CREATE TABLE SECTION(
    SECTION_IDENTIFIER INTEGER ,
    COURSE_NUMBER VARCHAR2(20),
    SEMESTER VARCHAR2(20),
    YEAR INTEGER,
    INSTRUCTOR VARCHAR2(30),
    FOREIGN KEY (COURSE_NUMBER)REFERENCES COURSE(COURSE_NUMBER),
    PRIMARY KEY (SECTION_IDENTIFIER)
)

CREATE TABLE GRADE_REPORT(
    STUDENT_NUMBER INTEGER,
    SECTION_IDENTIFIER INTEGER,
    GRADE CHAR(1),
    FOREIGN KEY (STUDENT_NUMBER)REFERENCES STUDENT(STUDENT_NUMBER),
    FOREIGN KEY (SECTION_IDENTIFIER)REFERENCES SECTION(SECTION_IDENTIFIER),
    PRIMARY KEY (STUDENT_NUMBER, SECTION_IDENTIFIER)
)

CREATE TABLE PREREQUISITE(
     COURSE_NUMBER VARCHAR2(20),
     PREREQUISITE_NUMBER VARCHAR2(20),
    FOREIGN KEY (COURSE_NUMBER)REFERENCES COURSE(COURSE_NUMBER)
)

